### ISSUE TITLE
Implementar Estado y Acción

### ISSUE THREAD

**Issue by Karlingas** [Karlingas/practicas_Inteligengtes#1]
Para implementar Estado y Acción tenemos que modificar tanto problema, y nodo como el bucle base.

**Comment by Karlingas** [comment]
Para solucionarlo hay que pensar el estado como el identificador de la interseccion que dentro contiene una lista de acciones que contienen inicio fin y coste de cada acción. Luego el nodo tiene esa información incluso podríamos no tener un parámetro acción y simplemente con un getter conseguir todas las acciones y luego la profundidad. En la clase problema crearemos todos los objetos dentro de problema

**Comment by vvvalero** [comment]
Para implementar primero el mejor. La heurística que se usa es: la distancia que hay hasta el nodo objetivo y la velocidad de la calle. A la hora de implementar la frontera, hay que utilizar una estructura de PriorityQueue que utiliza la forma (heurística,nodo). **CREO** que la PriorityQueue ordena automáticamente lo que nos permite sacar el primer elemento (el que mejor heurísitca tendrá).

**Comment by Karlingas** [comment]
ALE
